version: '2'
services:
  movies:
    build: ./movieservice
    image: movies/movieservice
    ports:
      - "8080:8080"
    depends_on:
      - db
      - approvals
    environment:
      MONGODB_URL: db
      APPROVALS_RPC_URL: http://approvals:8080/rpc
  approvals:
    build: ./approvalservice
    image: movies/approvalservice
    ports:
      - "8081:8080"
  db:
    image: mongo:3.6
    container_name: movies-db
    ports:
      - "27017:27017"
