apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.13.0 (84fa826)
  creationTimestamp: null
  labels:
    io.kompose.service: approvals
  name: approvals
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: approvals
    spec:
      containers:
      - image: movies/approvalservice
        imagePullPolicy: Never    # only use local images, built by `docker-compose build`
        name: approvals
        ports:
        - containerPort: 8080
        resources: {}
      restartPolicy: Always
status: {}
