apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.13.0 (84fa826)
  creationTimestamp: null
  labels:
    io.kompose.service: movies
  name: movies
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: movies
    spec:
      containers:
      - env:
        - name: APPROVALS_RPC_URL
          value: http://approvals:8080/rpc
        - name: MONGODB_URL
          value: db
        image: movies/movieservice
        imagePullPolicy: Never    # only use local images, built by `docker-compose build`
        name: movies
        ports:
        - containerPort: 8080
        resources: {}
      restartPolicy: Always
status: {}
